name: "Build: Android"
env:

  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Nostros
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: 'Install npm Dependencies'
        run: |
          cd android
          yarn install

      - name: Gradle version
        run: |
          cd android
          ./gradlew -version

      - name: Change wrapper permissions
        run: |
          cd android
          chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: |
          cd android
          ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: |
          cd android
          ./gradlew build

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: |
          cd android
          ./gradlew assemble

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ github.ref_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
