name: "Build: Android"
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4

      - name: 'Install npm Dependencies'
        run: |
          cd android
          yarn install

      - name: Gradle version
        run: |
          cd android
          ./gradlew -version

      - name: Change wrapper permissions
        run: |
          cd android
          chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: |
          cd android
          ./gradlew test

      # Create APK Release
      - name: Build apk release project (APK)
        run: |
          cd android
          ./gradlew assembleRelease

      # Noted For Output
      - name: 'Upload .apk Release Artifact (for Release)'
        uses: actions/upload-artifact@v3
        with:
          name: nostros-${{ github.ref_name }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk
